// Keep the PWA install useful without precaching heavyweight optional assets.
module.exports = {
  globPatterns: [
    '**/*.html',
    'css/*.css',
    'js/*.js',
    'js/search/*.js',
    'img/*.{ico,png,jpg,gif,webp,svg}',
    'opt-images/*.{jpg,png,webp}',
    'pluginsSrc/@fortawesome/fontawesome-free/css/all.min.css',
    'pluginsSrc/@fortawesome/fontawesome-free/webfonts/*.woff2',
    'pluginsSrc/medium-zoom/dist/medium-zoom.min.js',
    'pluginsSrc/instant.page/instantpage.js',
    'pluginsSrc/pjax/pjax.min.js'
  ],
  globIgnores: [
    '**/*.map',
    'fonts/**',
    'images/cosmic/**',
    'vendor/**',
    'js/daynight.js',
    'js/weather-panel.js',
    'js/weather-particles.js',
    'pluginsSrc/mathjax/**',
    'pluginsSrc/mermaid/**',
    'pluginsSrc/aplayer/**',
    'pluginsSrc/artalk/**',
    'pluginsSrc/valine/**',
    'pluginsSrc/waline/**',
    'pluginsSrc/twikoo/**',
    'pluginsSrc/gitalk/**',
    'pluginsSrc/disqusjs/**',
    'pluginsSrc/@docsearch/**',
    'pluginsSrc/@egjs/**',
    'pluginsSrc/@fancyapps/**',
    'pluginsSrc/abcjs/**',
    'pluginsSrc/algoliasearch/**',
    'pluginsSrc/blueimp-md5/**',
    'pluginsSrc/butterfly-extsrc/**',
    'pluginsSrc/chart.js/**',
    'pluginsSrc/katex/**',
    'pluginsSrc/node-snackbar/**',
    'pluginsSrc/pace-js/**',
    'pluginsSrc/prismjs/**',
    'pluginsSrc/typed.js/**',
    'pluginsSrc/vanilla-lazyload/**'
  ],
  maximumFileSizeToCacheInBytes: 900 * 1024,
  cleanupOutdatedCaches: true
};
